---
title: "Setting up for git"
author: "Broders"
date: "2023-11-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

#for a new project.  
```{r set the working directory}
setwd("/Users/hughbroders/documents/junk")
getwd()
```

#usethis package to initialize the git.  Could also just select the git repo option on the new project- new directory-new project option

```{r}
library(usethis)
use_git_config(user.name = "hughbroders", user.email = "hugh.broders@uwaterloo.ca")
use_git()
```

#just adding some committ testing junk some morejhgjhgjhgjhjh


againb

junk jghjhgjkgkugkgggugkh

#for a new project 
```{r set the working directory}
setwd("/Users/hughbroders/documents/junk")
getwd()
```

## Lets load some data and mess around


```{r bring in the csv file}
amnh_all<-read.table("/Users/hughbroders/documents/research/belize/1-data/amnh_full_datasheet/amnh8_24oct2023.csv", stringsAsFactors=FALSE, sep=",",header=T)
```

```{r seleect columns we need for pit work}
amnh<-amnh_all[,c("pit_number", "record_number","capture_number","genus","species","sex", "country","district","specific_location","net_site","method","lat", "long","expedition","ymd","time","repro_status","age")]
```

##For summary, lets create a genus species column
```{r make a new column of genus species}
amnh$genusspecies<-paste(amnh$genus,amnh$species,sep=" ")
```

